
= fastai.dataset

== Introduction and overview

```
...example...
```


== Class BaseDataset:Dataset

=== Arguments
*transform* (default None)

=== Methods

*get1item*

*__getitem__*

*__len__*

*get*

*get_n*:: Return number of elements in the dataset == len(self).

*get_c*:: Return number of classes in a dataset.

*get_sz*:: Return maximum size of an image in a dataset.

*get_x*:: Return i-th example (image, wav, etc).

*get_y*:: Return i-th label.

*is_multi*:: Returns true if this data set contains multiple labels per sample.

*is_reg*:: True if the data set is used to train regression models.

== Class FilesDataset:BaseDataset

=== Arguments
*fnames*

*transform*

*path*

=== Methods

*get_sz*

*get_x*

*get_n*

*resize_imgs*

*denorm*:: Reverse the normalization done to a batch of images.

Arguments:
    arr: of shape/size (N,3,sz,sz)

== Class FilesArrayDataset:FilesDataset

=== Arguments
*fnames*

*y*

*transform*

*path*

=== Methods

*get_y*

*get_c*

== Class FilesIndexArrayDataset:FilesArrayDataset

=== Methods

*get_c*

== Class FilesNhotArrayDataset:FilesArrayDataset

=== Methods

*is_multi*

== Class FilesIndexArrayRegressionDataset:FilesArrayDataset

=== Methods

*is_reg*

== Class ArraysDataset:BaseDataset

=== Arguments
*x*

*y*

*transform*

=== Methods

*get_x*

*get_y*

*get_n*

*get_sz*

== Class ArraysIndexDataset:ArraysDataset

=== Methods

*get_c*

*get_y*

== Class ArraysNhotDataset:ArraysDataset

=== Methods

*get_c*

*is_multi*

== Class ModelData

=== Arguments
*path*

*trn_dl*

*val_dl*

*test_dl* (default None)

=== Methods

*from_dls*

*is_reg*

*is_multi*

*trn_ds*

*val_ds*

*test_ds*

*trn_y*

*val_y*

== Class ImageData:ModelData

=== Arguments
*path*

*datasets*

*bs*

*num_workers*

*classes*

=== Methods

*get_dl*

*sz*

*c*

*resized*

*resize*

*get_ds*

== Class ImageClassifierData:ImageData

=== Methods

*from_arrays*:: Read in images and their labels given as numpy arrays

Arguments:
    path: a root path of the data (used for storing trained models, precomputed values, etc)
    trn: a tuple of training data matrix and target label/classification array (e.g. `trn=(x,y)` where `x` has the
        shape of `(5000, 784)` and `y` has the shape of `(5000,)`)
    val: a tuple of validation data matrix and target label/classification array.
    bs: batch size
    tfms: transformations (for data augmentations). e.g. output of `tfms_from_model`
    classes: a list of all labels/classifications
    num_workers: a number of workers
    test: a matrix of test data (the shape should match `trn[0]`)

Returns:
    ImageClassifierData

*from_paths*:: Read in images and their labels given as sub-folder names

Arguments:
    path: a root path of the data (used for storing trained models, precomputed values, etc)
    bs: batch size
    tfms: transformations (for data augmentations). e.g. output of `tfms_from_model`
    trn_name: a name of the folder that contains training images.
    val_name:  a name of the folder that contains validation images.
    test_name:  a name of the folder that contains test images.
    num_workers: number of workers

Returns:
    ImageClassifierData

*from_csv*:: Read in images and their labels given as a CSV file.

This method should be used when training image labels are given in an CSV file as opposed to
sub-directories with label names.

Arguments:
    path: a root path of the data (used for storing trained models, precomputed values, etc)
    folder: a name of the folder in which training images are contained.
    csv_fname: a name of the CSV file which contains target labels.
    bs: batch size
    tfms: transformations (for data augmentations). e.g. output of `tfms_from_model`
    val_idxs: index of images to be used for validation. e.g. output of `get_cv_idxs`.
        If None, default arguments to get_cv_idxs are used.
    suffix: suffix to add to image names in CSV file (sometimes CSV only contains the file name without file
            extension e.g. '.jpg' - in which case, you can set suffix as '.jpg')
    test_name: a name of the folder which contains test images.
    continuous: TODO
    skip_header: skip the first row of the CSV file.
    num_workers: number of workers

Returns:
    ImageClassifierData

*from_names_and_array*

== Module Functions

*get_cv_idxs*:: Get a list of index values for Validation set from a dataset

Arguments:
    n : int, Total number of elements in the data set.
    cv_idx : int, starting index [idx_start = cv_idx*int(val_pct*n)] 
    val_pct : (int, float), validation set percentage 
    seed : seed value for RandomState
    
Returns:
    list of indexes 

*resize_img*:: Enlarge or shrink a single image to scale, such that the smaller of the height or width dimension is equal to targ.

*resize_imgs*:: Enlarge or shrink a set of images in the same directory to scale, such that the smaller of the height or width dimension is equal to targ.
Note: 
-- This function is multithreaded for efficiency. 
-- When destination file or folder already exist, function exists without raising an error. 

*read_dir*

*read_dirs*:: Fetches name of all files in path in long form, and labels associated by extrapolation of directory names. 

*n_hot*:: one hot encoding by index. Returns array of length c, where all entries are 0, except for the indecies in ids

*folder_source*

*parse_csv_labels*:: Parse filenames and label sets from a CSV file.

This method expects that the csv file at path :fn: has two columns. If it
has a header, :skip_header: should be set to True. The labels in the
label set are expected to be space separated.

Arguments:
    fn: Path to a CSV file.
    skip_header: A boolean flag indicating whether to skip the header.

Returns:
    a four-tuple of (
        sorted image filenames,
        a dictionary of filenames and corresponding labels,
        a sorted set of unique labels,
        a dictionary of labels to their corresponding index, which will
        be one-hot encoded.
    )
.
:param cat_separator: the separator for the categories column

*nhot_labels*

*csv_source*

*dict_source*

*open_image*:: Opens an image using OpenCV given the file path.

Arguments:
    fn: the file path of the image

Returns:
    The image in RGB format as numpy array of floats normalized to range between 0.0 - 1.0

*split_by_idx*:: Split each array passed as *a, to a pair of arrays like this (elements selected by idxs,  the remaining elements)
This can be used to split multiple arrays containing training data to validation and training set.

:param idxs [int]: list of indexes selected
:param a list: list of np.array, each array should have same amount of elements in the first dimension
:return: list of tuples, each containing a split of corresponding array from *a.
        First element of each tuple is an array composed from elements selected by idxs,
        second element is an array of remaining elements.

