baseurl: /
collections:
  tooltips:
    output: false
company_name: fast.ai
default_badges:
  colab: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: Documentation for the fastai library
exclude:
- .idea/
- .gitignore
- vendor
feedback_disable: true
github_editme_path: null
google_analytics: UA-89522379-3
google_search: 000837339549978028235:ycech_9fn6e
highlighter: rouge
kramdown:
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
markdown: kramdown
output: web
plugins:
- jekyll-remote-theme
remote_theme: fastai/nbdev-jekyll-theme
repository: fastai/fastai
sidebars:
- home_sidebar
site_title: fastai
topnav_title: fastai
twitter_username: jeremyphoward
url: https://docs.fast.ai
use_math: true
