source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins

# Added at 2019-11-25 10:11:40 -0800 by jhoward:
gem "nokogiri", "< 1.11.1"
gem "jekyll", ">= 3.7"
gem "kramdown", ">= 2.3.1"
gem "jekyll-remote-theme"
