destination: _site/
url: "http://127.0.0.1:4012"
baseurl: "/product2-pdf"
port: 4012
output: pdf
product: product2
print_title: Product 2 documentation
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: product2_sidebar
