#!/usr/bin/env python3
from nbdev.export import script2notebook
from fastai2.core.script import *

@call_parse
def main(fname:Param("A filename or glob to convert", str)=None):
    script2notebook(fname=fname)
