#!/usr/bin/env python3

# This script facilitates trusting notebooks under examples.
#
# It should be run once immediately after running 'git clone'.
#
# It will install a post-merge hook in your .git/hooks/ directory.
#
# The installed hook will be executed by git automatically at the end
# of 'git pull' only if it triggered an actual merge event and that
# the latter was successful
#
# trust:
#   tools/trust-doc-nbs-install-hook
#
# distrust:
#   rm .git/hooks/post-merge
#
# note: windows users, not using bash emulation, will need to invoke this tool as:
#   python tools\trust-doc-nbs-install-hook

import sys
if sys.hexversion < 0x03060000: sys.exit("!!! Please re-run this script with python-3.6 or higher")

from shutil import copy2
from pathlib import Path

fin  = Path("tools")/"trust-doc-nbs"
fout = Path(".git")/"hooks"/"post-merge"

print("Installing .git/hooks/post-merge to automatically trust examples and docs_src notebooks")
copy2(fin, fout)
print("Success")
